FROM ubuntu:24.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    file \
    git \
    unzip \
    xz-utils \
    zip \
    libgtk-3-dev \
    libx11-dev \
    libappindicator3-dev \
    libdbus-1-dev \
    libgdk-pixbuf2.0-dev \
    libgl1-mesa-dev \
    libgles2-mesa-dev \
    libglu1-mesa-dev \
    libxcursor-dev \
    libxext-dev \
    libxfixes-dev \
    libxi-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxrender-dev \
    libxtst-dev \
    libxxf86vm-dev \
    lintian \
    && rm -rf /var/lib/apt/lists/*

# Install Flutter
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
ENV PATH="/usr/local/flutter/bin:$PATH"

RUN flutter precache

# Create a non-root user
RUN useradd -ms /bin/bash -d /home/builder builder
USER builder
WORKDIR /home/builder

# Copy the project
COPY . .

# Run the build and package script
CMD ["./build_and_package.sh"]
