// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjoUZYOf_F9LOv1mNp8NjtlcVQOQ4tKv8',
    appId: '1:154919701865:web:2237241bc089a861d541f8',
    messagingSenderId: '154919701865',
    projectId: 'cloudtolocalllm',
    authDomain: 'cloudtolocalllm.firebaseapp.com',
    storageBucket: 'cloudtolocalllm.firebasestorage.app',
    measurementId: 'G-CR3LEXV62H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0hh_KOicOmox5XxlcqhpE58lJxSuqIQ',
    appId: '1:154919701865:android:3c5e762f6d5d4867d541f8',
    messagingSenderId: '154919701865',
    projectId: 'cloudtolocalllm',
    storageBucket: 'cloudtolocalllm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9l-u9KbOkogsCLc9Q0Hassa7u72DDi8',
    appId: '1:154919701865:ios:b9f4d3d01800ba08d541f8',
    messagingSenderId: '154919701865',
    projectId: 'cloudtolocalllm',
    storageBucket: 'cloudtolocalllm.firebasestorage.app',
    iosBundleId: 'com.example.cloudtolocalllmDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi9l-u9KbOkogsCLc9Q0Hassa7u72DDi8',
    appId: '1:154919701865:ios:b9f4d3d01800ba08d541f8',
    messagingSenderId: '154919701865',
    projectId: 'cloudtolocalllm',
    storageBucket: 'cloudtolocalllm.firebasestorage.app',
    iosBundleId: 'com.example.cloudtolocalllmDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjoUZYOf_F9LOv1mNp8NjtlcVQOQ4tKv8',
    appId: '1:154919701865:web:c6804cd7b203643ed541f8',
    messagingSenderId: '154919701865',
    projectId: 'cloudtolocalllm',
    authDomain: 'cloudtolocalllm.firebaseapp.com',
    storageBucket: 'cloudtolocalllm.firebasestorage.app',
    measurementId: 'G-DNEX4JGG1L',
  );
}
