// This file is kept for reference but is no longer used.
// The application has been migrated from Firebase Authentication to Auth0.
// For authentication configuration, please refer to lib/auth0_options.dart

// If you need to restore Firebase functionality:
// 1. Re-add the Firebase dependencies to pubspec.yaml
// 2. Restore the original content of this file
// 3. Update main.dart to initialize Firebase

// Original file generated by FlutterFire CLI.
